##
POST http://localhost:4004/odata/v4/audit-logging-and-reporting/syncServiceLogs
Content-Type: application/json

{}

### fetch the service auditlogs
GET http://localhost:4004/odata/v4/audit-logging-and-reporting/ServiceAuditReport

###
POST http://localhost:4004/odata/v4/audit-logging-and-reporting/clearEntitlements
Content-Type: application/json

{}

### create the service keys for subaccount
POST http://localhost:4004/odata/v4/audit-logging-and-reporting/BTPConnection
Content-Type: application/json

{
    "subaccountId": "396100c1-7413-4eb4-b435-2c85c2772979",
    "subaccountName": "510027cetrial",
    "serviceType": "SERVICE_MANAGER",
    "tokenUrl": "https://510027cetrial.authentication.us10.hana.ondemand.com",
    "apiBaseUrl": "https://service-manager.cfapps.us10.hana.ondemand.com",
    "clientId": "sb-f942a6e2-b99c-4044-9530-0467af440312!b687901|service-manager!b1476",
    "clientSecret": "72f74ae8-c835-441d-aa38-cfc241b75022$KBQyFoveGwu2X5ydKDVvtm1R21wqhkFM30HXywgGlN0=",
    "region": "us10",
    "active": true
}

### create the service keys for audit logs service
POST http://localhost:4004/odata/v4/audit-logging-and-reporting/BTPConnection
Content-Type: application/json

{
    "subaccountId": "396100c1-7413-4eb4-b435-2c85c2772979",
    "subaccountName": "510027cetrial",
    "serviceType": "AUDIT_LOG",
    "tokenUrl": "https://510027cetrial.authentication.us10.hana.ondemand.com",
    "apiBaseUrl": "https://auditlog-management.cfapps.us10.hana.ondemand.com",
    "clientId": "sb-5e5d6fff-b289-414d-a6af-21eac41779ca!b687901|auditlog-management!b1187",
    "clientSecret": "906c4175-8e6b-432a-b53f-b2bc44a8eda9$v91K7NutiJ-L8zyG-0zg_bYGkIXGdk5ZlJIH-doK8uk=",
    "region": "us10",
    "active": true
}

### fetch all the subaccount client ids and service key
GET  http://localhost:4004/odata/v4/audit-logging-and-reporting/BTPConnection

### user audit
POST http://localhost:4004/odata/v4/audit-logging-and-reporting/ReportSyncStatus
Content-Type: application/json

{
    "reportName": "USER_AUDIT",
    "lastSyncStatus": "SUCCESS",
    "isRunning": false,
    "message": "Not synchronized yet"
}
### role audit
POST http://localhost:4004/odata/v4/audit-logging-and-reporting/ReportSyncStatus
Content-Type: application/json

{
    "reportName": "ROLE_AUDIT",
    "lastSyncStatus": "SUCCESS",
    "isRunning": false,
    "message": "Not synchronized yet"
}

### configuration report
POST http://localhost:4004/odata/v4/audit-logging-and-reporting/ReportSyncStatus
Content-Type: application/json

{
    "reportName": "CONFIGURATION",
    "lastSyncStatus": "SUCCESS",
    "isRunning": false,
    "message": "Not synchronized yet"
}
### service audit report
POST http://localhost:4004/odata/v4/audit-logging-and-reporting/ReportSyncStatus
Content-Type: application/json

{
    "reportName": "SERVICE_AUDIT",
    "lastSyncStatus": "SUCCESS",
    "isRunning": false,
    "message": "Not synchronized yet"
}

### fetch report status
GET http://localhost:4004/odata/v4/audit-logging-and-reporting/ReportSyncStatus


### action to sync role audit logs
POST http://localhost:4004/odata/v4/audit-logging-and-reporting/syncRoleLogs
Content-Type: application/json

{}

###
GET http://localhost:4004/odata/v4/audit-logging-and-reporting/ConfigurationReport

### deleting role record from status table
PUT  http://localhost:4004/odata/v4/audit-logging-and-reporting/ReportSyncStatus('11111111-1111-4111-8111-111111111111')
Content-Type: application/json

{
    "ID": "11111111-1111-4111-8111-111111111111",
    "createdAt": null,
    "createdBy": null,
    "isRunning": false,
    "lastRunAt": null,
    "lastSyncAt": "1970-01-01T00:00:00Z",
    "lastSyncBy": null,
    "lastSyncStatus": "SUCCESS",
    "message": "Not synchronized yet",
    "modifiedAt": null,
    "modifiedBy": null,
    "reportName": "USER_AUDIT"
}
###
POST http://localhost:4004/odata/v4/audit-logging-and-reporting/BTPServiceTypeVH
Content-Type: application/json

{
    "code":"SAAS_MANAGER"
}

###

POST http://localhost:4004/odata/v4/audit-logging-and-reporting/syncUserAuditLogs
Content-Type: application/json

{}


### Synchronize Configuration Audit Logs
POST http://localhost:4004/odata/v4/audit-logging-and-reporting/syncConfigurationAuditLogs
Content-Type: application/json

{}


